name: Waka Readme

on:
  schedule:
    # Runs at 12am on first of the month. IST
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_SHORT_INFO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMELINE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
#           SHOW_DAYS_OF_WEEK: "True"
#           SHOW_OS: "True"
#           SHOW_PROJECTS: "False"
#           SHOW_COMMIT: "True"
#           SHOW_LANGUAGE: "True"
#           SHOW_EDITORS: "True"
#           SHOW_TIMEZONE: "False"
#           SHOW_LANGUAGE_PER_REPO: "True"
#           SHOW_LOC_CHART: "False"

  update-gist:
    runs-on: ubuntu-latest
    needs: update-readme
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ef5164cd50f0e30ca002952d3339478d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
