name: Waka Readme

on:
  schedule:
    # Runs at 12am on first of the month. IST
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:          
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ef5164cd50f0e30ca002952d3339478d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
          
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE : "True"
